/**
 * TEMPO NATIVE WALLET
  * Fixed & Optimized for Codespaces
   */
   import React, { useState, useEffect } from 'react';
   import {
     SafeAreaView,
       ScrollView,
         StatusBar,
           StyleSheet,
             Text,
               useColorScheme,
                 View,
                   TouchableOpacity,
                     TextInput,
                       Alert,
                         ActivityIndicator
                         } from 'react-native';

                         import { createPublicClient, http, formatUnits } from 'viem';
                         import { tempoTestnet } from 'viem/chains';

                         const TEMPO_RPC = 'https://rpc.moderato.tempo.xyz';

                         const client = createPublicClient({
                           chain: tempoTestnet,
                             transport: http(TEMPO_RPC),
                             });

                             const DEMO_ADDRESS = '0x1234567890123456789012345678901234567890'; 

                             function App(): JSX.Element {
                               const isDarkMode = useColorScheme() === 'dark';
                                 const [balance, setBalance] = useState('0.00');
                                   const [feeToken, setFeeToken] = useState('Loading...');
                                     const [address, setAddress] = useState(DEMO_ADDRESS);
                                       const [loading, setLoading] = useState(false);

                                         const fetchTempoData = async () => {
                                             setLoading(true);
                                                 try {
                                                       console.log('Fetching Tempo Data...');
                                                             // 1. Ask Tempo: "What token does this user pay gas with?"
                                                                   const feeTokenData: any = await client.request({
                                                                           method: 'tempo_getUserToken',
                                                                                   params: [address as `0x${string}`],
                                                                                         } as any);

                                                                                               setFeeToken(feeTokenData.symbol || 'USDC');

                                                                                                     // 2. Get Balance of THAT token (Not ETH)
                                                                                                           const balanceData = await client.readContract({
                                                                                                                   address: feeTokenData.address,
                                                                                                                           abi: [{
                                                                                                                                     constant: true,
                                                                                                                                               inputs: [{ name: 'account', type: 'address' }],
                                                                                                                                                         name: 'balanceOf',
                                                                                                                                                                   outputs: [{ name: '', type: 'uint256' }],
                                                                                                                                                                             type: 'function'
                                                                                                                                                                                     }],
                                                                                                                                                                                             functionName: 'balanceOf',
                                                                                                                                                                                                     args: [address],
                                                                                                                                                                                                           });

                                                                                                                                                                                                                 const formatted = formatUnits(balanceData as bigint, 18);
                                                                                                                                                                                                                       setBalance(Number(formatted).toFixed(2));
                                                                                                                                                                                                                           } catch (error) {
                                                                                                                                                                                                                                 console.log('Error fetching data (expected if address is empty)', error);
                                                                                                                                                                                                                                       setBalance('0.00');
                                                                                                                                                                                                                                             setFeeToken('pathUSD');
                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                     setLoading(false);
                                                                                                                                                                                                                                                       };

                                                                                                                                                                                                                                                         useEffect(() => { fetchTempoData(); }, []);

                                                                                                                                                                                                                                                           return (
                                                                                                                                                                                                                                                               <SafeAreaView style={styles.container}>
                                                                                                                                                                                                                                                                     <StatusBar barStyle="light-content" />
                                                                                                                                                                                                                                                                           <View style={styles.header}>
                                                                                                                                                                                                                                                                                   <Text style={styles.headerTitle}>Tempo<Text style={styles.headerBold}>Wallet</Text></Text>
                                                                                                                                                                                                                                                                                           <View style={styles.badge}><Text style={styles.badgeText}>Testnet</Text></View>
                                                                                                                                                                                                                                                                                                 </View>

                                                                                                                                                                                                                                                                                                       <ScrollView contentContainerStyle={styles.scroll}>
                                                                                                                                                                                                                                                                                                               <View style={styles.card}>
                                                                                                                                                                                                                                                                                                                         <Text style={styles.label}>Total Balance</Text>
                                                                                                                                                                                                                                                                                                                                   <View style={styles.row}>
                                                                                                                                                                                                                                                                                                                                               <Text style={styles.currency}>$</Text>
                                                                                                                                                                                                                                                                                                                                                           <Text style={styles.balance}>{balance}</Text>
                                                                                                                                                                                                                                                                                                                                                                     </View>
                                                                                                                                                                                                                                                                                                                                                                               <Text style={styles.subtext}>Gas Source: {feeToken}</Text>
                                                                                                                                                                                                                                                                                                                                                                                       </View>

                                                                                                                                                                                                                                                                                                                                                                                               <View style={styles.actionRow}>
                                                                                                                                                                                                                                                                                                                                                                                                         <TouchableOpacity style={styles.btnPrimary} onPress={() => Alert.alert('Sent!')}>
                                                                                                                                                                                                                                                                                                                                                                                                                     <Text style={styles.btnText}>Send</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                               </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                         <TouchableOpacity style={styles.btnSecondary} onPress={fetchTempoData}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                     <Text style={styles.btnTextSec}>{loading ? '...' : 'Refresh'}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                               </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </View>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <View style={styles.inputContainer}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <Text style={styles.labelDark}>Address</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <TextInput 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               style={styles.input} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           value={address} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       onChangeText={setAddress} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   placeholderTextColor="#666"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </ScrollView>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </SafeAreaView>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   container: { flex: 1, backgroundColor: '#111' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     header: { padding: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       headerTitle: { color: '#fff', fontSize: 24 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         headerBold: { fontWeight: 'bold', color: '#4F86F7' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           badge: { backgroundColor: '#222', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 5 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             badgeText: { color: '#888', fontSize: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               scroll: { padding: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 card: { backgroundColor: '#1A1A1A', borderRadius: 20, padding: 30, marginBottom: 25 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   label: { color: '#888', textTransform: 'uppercase', fontSize: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     row: { flexDirection: 'row', marginVertical: 10, alignItems: 'flex-start' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       currency: { color: '#4F86F7', fontSize: 24, marginTop: 6, marginRight: 4 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         balance: { color: '#fff', fontSize: 48, fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           subtext: { color: '#444', fontSize: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             actionRow: { flexDirection: 'row', marginBottom: 30 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               btnPrimary: { backgroundColor: '#4F86F7', flex: 1, padding: 15, borderRadius: 12, alignItems: 'center', marginRight: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 btnSecondary: { backgroundColor: '#222', flex: 1, padding: 15, borderRadius: 12, alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   btnText: { color: '#fff', fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     btnTextSec: { color: '#fff' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       inputContainer: { marginBottom: 30 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         labelDark: { color: '#666', marginBottom: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           input: { backgroundColor: '#222', color: '#fff', padding: 15, borderRadius: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           export default App;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           EOF

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           # 7. CI/CD: Create the APK Builder (Using v4 to prevent deprecation error)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           mkdir -p .github/workflows
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           cat > .github/workflows/apk.yml <<EOF
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           name: Build APK
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           on: push
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           jobs:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             build:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 runs-on: ubuntu-latest
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     steps:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           - uses: actions/checkout@v4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 - uses: actions/setup-java@v3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         with:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   distribution: 'zulu'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             java-version: '17'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   - run: npm install
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         - run: cd android && chmod +x gradlew && ./gradlew assembleRelease
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               - uses: actions/upload-artifact@v4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       with:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 name: tempo-wallet-apk
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           path: android/app/build/outputs/apk/release/app-release.apk
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           EOF

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           # 8. PUSH: Send to GitHub to start building
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           git add .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           git commit -m "Fixed React Native Template Error"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           git push
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
